name: Windows RDP
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin Password123
          echo "RDP HAZIR!"
      - name: Keep Alive
        run: timeout 21600
