name: Windows RDP
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          net user runneradmin Hack12345
          
      - name: Show IP
        run: |
          $IP = (Invoke-WebRequest -Uri "https://api.ipify.org" -UseBasicParsing).Content
          echo "============================================"
          echo "           RDP BILGILERI"
          echo "============================================"
          echo "IP: $IP"
          echo "Kullanici: runneradmin"
          echo "Sifre: Hack12345"
          echo "============================================"
          
      - name: Keep Alive 6 Hours
        run: Start-Sleep -Seconds 21600
        timeout-minutes: 360
